### ISSUE TITLE
Working only with the saved images

### ISSUE THREAD

**Issue by Kuldeep363** [benhowdle89/grade#23]
I loved grade js and i worked too many times with this but one day when I was working with an API, images loaded from the link of an image provided in API, but grade js shows exception and doesn't work.

Exception looks like:

Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at Grade.getImageData (http://127.0.0.1:5500/cars/static/cars/js/grade.js:41:38)
    at Grade.render (http://127.0.0.1:5500/cars/static/cars/js/grade.js:177:18)
    at Grade.readImage (http://127.0.0.1:5500/cars/static/cars/js/grade.js:36:18)
    at new Grade (http://127.0.0.1:5500/cars/static/cars/js/grade.js:28:14)
    at init (http://127.0.0.1:5500/cars/static/cars/js/grade.js:187:21)
    at http://127.0.0.1:5500/cars/static/cars/js/grade.js:198:16
    at Array.map (<anonymous>)
    at module.exports (http://127.0.0.1:5500/cars/static/cars/js/grade.js:197:90)
    at http://127.0.0.1:5500/cars/templates/cars/try.html:49:13
getImageData @ grade.js:41
render @ grade.js:177
readImage @ grade.js:36
Grade @ grade.js:28
init @ grade.js:187
(anonymous) @ grade.js:198
module.exports @ grade.js:197
(anonymous) @ try.html:49
load (async)
(anonymous) @ try.html:48

**Comment by sensimedia** [comment]
Try adding crossorigin="anonymous" to your image tag. 
Eg: `<img src="image.jpg" crossorigin="anonymous">`
